---
title: "R Notebook"
output: html_notebook
---



```{r}

library(package = "tidyverse")
library(package = "reshape2")

  # Mapping  support
  library(package = "maps")
  library(package = "mapproj")
  library(package = "rgdal")
  library(package = "rgeos")

```




```{r}

URL_Root = "http://kyrill.ias.sdsmt.edu:8080/thredds/fileServer/LOCA_NGP/climatology/DERIVED/YEARLY/KOEPPEN/"
URL_Root = "/maelstrom2/LOCA_GRIDDED_ENSEMBLES/LOCA_NGP/climatology/DERIVED/YEARLY/KOEPPEN/"

```





```{r}

###############################################################
#
# Ensemble Members

  ensembles = c( "ACCESS1-0_r1i1p1",
                 "ACCESS1-3_r1i1p1",
                 "CCSM4_r6i1p1",
                 "CESM1-BGC_r1i1p1",
                 "CESM1-CAM5_r1i1p1",
                 "CMCC-CMS_r1i1p1",
                 "CMCC-CM_r1i1p1",
                 "CNRM-CM5_r1i1p1",
                 "CSIRO-Mk3-6-0_r1i1p1",
                 "CanESM2_r1i1p1",
                 "FGOALS-g2_r1i1p1",
                 "GFDL-CM3_r1i1p1",
                 "GFDL-ESM2G_r1i1p1",
                 "GFDL-ESM2M_r1i1p1",
                 "HadGEM2-AO_r1i1p1",
                 "HadGEM2-CC_r1i1p1",
                 "HadGEM2-ES_r1i1p1",
                 "IPSL-CM5A-LR_r1i1p1",
                 "IPSL-CM5A-MR_r1i1p1",
                 "MIROC-ESM_r1i1p1",
                 "MIROC5_r1i1p1",
                 "MPI-ESM-LR_r1i1p1",
                 "MPI-ESM-MR_r1i1p1",
                 "MRI-CGCM3_r1i1p1",
                 "NorESM1-M_r1i1p1",
                 "bcc-csm1-1-m_r1i1p1" )
  
  
  ensembles = c( "ACCESS1-0_r1i1p1" )
#
###############################################################

```



                         
```{r}

koeppen_names  =    c('Af',  # Af
                      'Am',  # Am
                      'As',  # As
                      'Aw',  # Aw
                      'BWk', # BWk
                      'BWh', # BWh
                      'BSk', # BSk
                      'BSh', # BSh
                      'Cfa', # Cfa
                      'Cfb', # Cfb
                      'Cfc', # Cfc
                      'Csa', # Csa
                      'Csb', # Csb
                      'Csc', # Csc
                      'Cwa', # Cwa
                      'Cwb', # Cwb
                      'Cwc', # Cwc
                      'Dfa', # Dfa
                      'Dfb', # Dfb
                      'Dfc', # Dfc
                      'Dfd', # Dfd
                      'Dsa', # Dsa
                      'Dsb', # Dsb
                      'Dsc', # Dsc
                      'Dsd', # Dsd
                      'Dwa', # Dwa
                      'Dwb', # Dwb
                      'Dwc', # Dwc
                      'Dwd', # Dwd
                      'EF',  # EF
                      'ET')  # ET

koeppen_colors =    c('#0009FE',  # Af
                      '#006CFF',  # Am
                      '#3D9FF9',  # As
                      '#3D9FF9',  # Aw
                      
                      '#FE8B8A', # BWk
                      '#FE0001', # BWh
                      
                      '#FFD658', # BSk
                      '#F49803', # BSh
                      
                      '#BFFF45', # Cfa
                      '#5CFF2D', # Cfb
                      '#2DBF03', # Cfc
                      
                      '#FFFF03', # Csa
                      '#BFBF02', # Csb
                      '#8B8B01', # Csc
                      
                      '#8BFF8B', # Cwa
                      '#58BF59', # Cwb
                      '#2C8B2D', # Cwc
                      
                      '#00FFFF', # Dfa
                      '#31C0FF', # Dfb
                      '#007372', # Dfc
                      '#003D53', # Dfd
                      
                      '#FF03FE', # Dsa
                      '#BE02C0', # Dsb
                      '#8B2C8A', # Dsc
                      '#895888', # Dsd
                      
                      '#A1A8FF', # Dwa
                      '#4F6CD6', # Dwb
                      '#4348AC', # Dwc
                      '#2C027C', # Dwd
                      
                      '#5D5D5D', # EF
                      '#A9A9A9') # ET


koeppen_colors = as.array(koeppen_colors)
names(koeppen_colors) = koeppen_names
                      


```
        

```{r}

  Ensemble = ensembles[1]
  {



    load(file    = (str_c(URL_Root,
                             "KOEPPEN_HISTO_", 
                             Ensemble,
                             ".Rdata")),
         verbose = TRUE)
    
    load(file    = (str_c(URL_Root,
                             "KOEPPEN_RCP45_", 
                             Ensemble,
                             ".Rdata")),
         verbose = TRUE)

        
    load(file    = (str_c(URL_Root,
                             "KOEPPEN_RCP85_", 
                             Ensemble,
                             ".Rdata")),
         verbose = TRUE)




    # tidy koeppen arrays

    koeppen = melt(data       = koeppen_histo,
                   varnames   = c("Longitude",
                                  "Latitude",
                                  "Year"),
                   value.name = "Class")

    koeppen$Ensemble = Ensemble
    koeppen$Scenario = "Historical"
    remove(koeppen_histo)
   
    
    deleteme = melt(data       = koeppen_rcp45,
                    varnames   = c("Longitude",
                                  "Latitude",
                                  "Year"),
                    value.name = "Class")

    deleteme$Ensemble = Ensemble
    deleteme$Scenario = "RCP 4.5"
    
    koeppen = rbind(koeppen,deleteme)
    
    remove(koeppen_rcp45)
    remove(deleteme)
  

        
    deleteme = melt(data       = koeppen_rcp85,
                    varnames   = c("Longitude",
                                  "Latitude",
                                  "Year"),
                    value.name = "Class")

    deleteme$Ensemble = Ensemble
    deleteme$Scenario = "RCP 8.5"
    
     koeppen = rbind(koeppen,deleteme)
    remove(koeppen_rcp85)
    remove(deleteme)
    
    
    koeppen$Scenario = as.factor(koeppen$Scenario)

    
  }

  years     = 1950:2099
  Longitude = unique(koeppen$Longitude)
  Latitude  = unique(koeppen$Latitude)
  
  
  koeppen = koeppen %>%
     mutate(Class=replace(Class, Class=="BSk'", "BSk")) %>%
     as.data.frame()

  
  koeppen = koeppen %>%
     mutate(Class=replace(Class, Class=="BWk'", "BWk")) %>%
     as.data.frame()
  
  koeppen$Class = as.character(koeppen$Class)
  
  koeppen$Class =    factor(x      = koeppen$Class, 
                            levels = koeppen_names)
  
  koeppen$Year = as.numeric(koeppen$Year)


```


            coord_proj(xlim=c(min(Longitude), max(Longitude)),
                         ylim=c(min(Latitude),  max(Latitude)) )  +
# 6 Import Mapping Data

US and Lake Data is Available in R.  Canadian Data isn't so we have a custom polygon library

```{r}
load(file = "./canadian_provinces.Rdata")
# inported field is canada_data = canadian_provinces


usa_data   = map_data(map="state", 
                      xlim=c(-114.2812, -86.21875),  
                      ylim=c (33.96875,  52.78125) ) 
water_data = map_data(map="lakes", 
                      xlim=c(-114.2812,-86.21875),  
                      ylim=c( 33.96875, 52.78125) ) 

```

   
   
```{r}
getmode <- function(v) {
   uniqv <- unique(v)
   uniqv[which.max(tabulate(match(v, uniqv)))]
}

```
                 

```{r}

  year_start = seq(from = 1950,
                   to   = 2095,
                   by    =   1)

  year_end   = year_start + 4

  Ensemble = ensembles[1]
  {
    ens_m = which(ensembles == Ensemble)
    
    for (Year in year_start)
    {
      print(str_c("Processing ", Year))
      year_k      = which(Year == year_start)
      koeppen_period = koeppen %>% filter((Ensemble == ensembles[ens_m]) &
                                          (Year     >= year_start[year_k]) &
                                          (Year     <= year_end[year_k])  )
      
      print(unique(koeppen_period$Year))
      
      
      if ((2005 %in% year_start[year_k]:year_end[year_k]) & 
          (2006 %in% year_start[year_k]:year_end[year_k]) )
      {
        print("Strattling Point of Divergence")
        koeppen_period_hist = koeppen_period %>% 
                                 filter(Scenario == "Historical")
        
        koeppen_period_hist$Scenario = "RCP 4.5"
        
        koeppen_period = koeppen_period %>%
            mutate(Scenario=replace(Scenario, Scenario=="Historical", "RCP 8.5")) %>%
            as.data.frame()
        
        koeppen_period = rbind(koeppen_period_hist, koeppen_period)
        remove(koeppen_period_hist)
        
        
        
      }
      

      koeppen_sub = koeppen_period %>% group_by(Longitude,Latitude,Scenario) %>% 
        summarise (Class = getmode(Class))
      
      mymap = ggplot(data   =   koeppen_sub)  + 
  
               aes(x     = Longitude,
                   y     = Latitude) +
  
               facet_grid(cols = vars(Scenario)) +
  
               theme_bw() + 
        
               theme(strip.background = element_rect(fill=NA),
                     aspect.ratio=1)+
  
               labs(title    = "LOCA Climate Ensemble Analyses",
                    subtitle = str_c(year_start[year_k],"-",
                                     year_end[year_k],
                                     " Köppen-Geigger for LOCA Member ", 
                                     Ensemble))+
  
               xlab(label = "Longitude") + 
  
               ylab(label = "Latitude") +         coord_map() +
        
              guides(fill=guide_legend(ncol=2)) +

        
               coord_cartesian(xlim=c(min(Longitude), max(Longitude)),
                               ylim=c(min(Latitude),  max(Latitude)) )  +
        
              # xlim(min(Longitude), max(Longitude)) +
              # ylim(min(Latitude), max(Latitude)) +
        
               scale_fill_manual(values = koeppen_colors,drop = FALSE) +
        
               geom_raster(mapping = aes(fill=Class)) +
        
               geom_polygon(data  = usa_data,
                                    mapping = aes(x     =   long, 
                                                  y     =    lat,
                                                  group =  group),
                                    fill  = NA, 
                                    color = "black")  + 
  
               geom_polygon(data  = water_data,
                                    mapping = aes(x     =   long, 
                                                  y     =    lat,
                                                  group =  group),
                                    fill  = NA, 
                                    color = "black")  + 
            
               geom_polygon(data  = canadian_provinces,
                                    mapping = aes(x     =   long, 
                                                  y     =    lat,
                                                  group =  group),
                                    fill  = NA, 
                                    color = "black") 

        
      ggsave(filename = str_c("./Koeppen_Map_",
                        Ensemble,
                        '_',
                        year_start[year_k],"-",
                        year_end[year_k],
                        "_LOCA_MAP.png",
                        sep = ""),
             plot = mymap,
             device = "png",
             width = 10.5, height = 5.75)
      print(mymap)
      
             
      
    }


    
  }

```

